export interface Country {
  id: number
  alpha2: string
  alpha3: string
  flag: any
  zh: string
  en: string
}

export const countries = {
  af: { id: 4, alpha2: "af", alpha3: "afg", flag: require("../assets/flags/32x32/af.png"), zh: "阿富汗", en: "Afghanistan" },
  al: { id: 8, alpha2: "al", alpha3: "alb", flag: require("../assets/flags/32x32/al.png"), zh: "阿尔巴尼亚", en: "Albania" },
  dz: { id: 12, alpha2: "dz", alpha3: "dza", flag: require("../assets/flags/32x32/dz.png"), zh: "阿尔及利亚", en: "Algeria" },
  ad: { id: 20, alpha2: "ad", alpha3: "and", flag: require("../assets/flags/32x32/ad.png"), zh: "安道尔", en: "Andorra" },
  ao: { id: 24, alpha2: "ao", alpha3: "ago", flag: require("../assets/flags/32x32/ao.png"), zh: "安哥拉", en: "Angola" },
  ag: { id: 28, alpha2: "ag", alpha3: "atg", flag: require("../assets/flags/32x32/ag.png"), zh: "安提瓜和巴布达", en: "Antigua and Barbuda" },
  ar: { id: 32, alpha2: "ar", alpha3: "arg", flag: require("../assets/flags/32x32/ar.png"), zh: "阿根廷", en: "Argentina" },
  am: { id: 51, alpha2: "am", alpha3: "arm", flag: require("../assets/flags/32x32/am.png"), zh: "亚美尼亚", en: "Armenia" },
  au: { id: 36, alpha2: "au", alpha3: "aus", flag: require("../assets/flags/32x32/au.png"), zh: "澳大利亚", en: "Australia" },
  at: { id: 40, alpha2: "at", alpha3: "aut", flag: require("../assets/flags/32x32/at.png"), zh: "奥地利", en: "Austria" },
  az: { id: 31, alpha2: "az", alpha3: "aze", flag: require("../assets/flags/32x32/az.png"), zh: "阿塞拜疆", en: "Azerbaijan" },
  bs: { id: 44, alpha2: "bs", alpha3: "bhs", flag: require("../assets/flags/32x32/bs.png"), zh: "巴哈马", en: "Bahamas" },
  bh: { id: 48, alpha2: "bh", alpha3: "bhr", flag: require("../assets/flags/32x32/bh.png"), zh: "巴林", en: "Bahrain" },
  bd: { id: 50, alpha2: "bd", alpha3: "bgd", flag: require("../assets/flags/32x32/bd.png"), zh: "孟加拉国", en: "Bangladesh" },
  bb: { id: 52, alpha2: "bb", alpha3: "brb", flag: require("../assets/flags/32x32/bb.png"), zh: "巴巴多斯", en: "Barbados" },
  by: { id: 112, alpha2: "by", alpha3: "blr", flag: require("../assets/flags/32x32/by.png"), zh: "白俄罗斯", en: "Belarus" },
  be: { id: 56, alpha2: "be", alpha3: "bel", flag: require("../assets/flags/32x32/be.png"), zh: "比利时", en: "Belgium" },
  bz: { id: 84, alpha2: "bz", alpha3: "blz", flag: require("../assets/flags/32x32/bz.png"), zh: "伯利兹", en: "Belize" },
  bj: { id: 204, alpha2: "bj", alpha3: "ben", flag: require("../assets/flags/32x32/bj.png"), zh: "贝宁", en: "Benin" },
  bt: { id: 64, alpha2: "bt", alpha3: "btn", flag: require("../assets/flags/32x32/bt.png"), zh: "不丹", en: "Bhutan" },
  bo: { id: 68, alpha2: "bo", alpha3: "bol", flag: require("../assets/flags/32x32/bo.png"), zh: "玻利维亚", en: "Bolivia (Plurinational State of)" },
  ba: { id: 70, alpha2: "ba", alpha3: "bih", flag: require("../assets/flags/32x32/ba.png"), zh: "波黑", en: "Bosnia and Herzegovina" },
  bw: { id: 72, alpha2: "bw", alpha3: "bwa", flag: require("../assets/flags/32x32/bw.png"), zh: "博茨瓦纳", en: "Botswana" },
  br: { id: 76, alpha2: "br", alpha3: "bra", flag: require("../assets/flags/32x32/br.png"), zh: "巴西", en: "Brazil" },
  bn: { id: 96, alpha2: "bn", alpha3: "brn", flag: require("../assets/flags/32x32/bn.png"), zh: "文莱", en: "Brunei Darussalam" },
  bg: { id: 100, alpha2: "bg", alpha3: "bgr", flag: require("../assets/flags/32x32/bg.png"), zh: "保加利亚", en: "Bulgaria" },
  bf: { id: 854, alpha2: "bf", alpha3: "bfa", flag: require("../assets/flags/32x32/bf.png"), zh: "布基纳法索", en: "Burkina Faso" },
  bi: { id: 108, alpha2: "bi", alpha3: "bdi", flag: require("../assets/flags/32x32/bi.png"), zh: "布隆迪", en: "Burundi" },
  cv: { id: 132, alpha2: "cv", alpha3: "cpv", flag: require("../assets/flags/32x32/cv.png"), zh: "佛得角", en: "Cabo Verde" },
  kh: { id: 116, alpha2: "kh", alpha3: "khm", flag: require("../assets/flags/32x32/kh.png"), zh: "柬埔寨", en: "Cambodia" },
  cm: { id: 120, alpha2: "cm", alpha3: "cmr", flag: require("../assets/flags/32x32/cm.png"), zh: "喀麦隆", en: "Cameroon" },
  ca: { id: 124, alpha2: "ca", alpha3: "can", flag: require("../assets/flags/32x32/ca.png"), zh: "加拿大", en: "Canada" },
  cf: { id: 140, alpha2: "cf", alpha3: "caf", flag: require("../assets/flags/32x32/cf.png"), zh: "中非", en: "Central African Republic" },
  td: { id: 148, alpha2: "td", alpha3: "tcd", flag: require("../assets/flags/32x32/td.png"), zh: "乍得", en: "Chad" },
  cl: { id: 152, alpha2: "cl", alpha3: "chl", flag: require("../assets/flags/32x32/cl.png"), zh: "智利", en: "Chile" },
  cn: { id: 156, alpha2: "cn", alpha3: "chn", flag: require("../assets/flags/32x32/cn.png"), zh: "中国", en: "China" },
  co: { id: 170, alpha2: "co", alpha3: "col", flag: require("../assets/flags/32x32/co.png"), zh: "哥伦比亚", en: "Colombia" },
  km: { id: 174, alpha2: "km", alpha3: "com", flag: require("../assets/flags/32x32/km.png"), zh: "科摩罗", en: "Comoros" },
  cg: { id: 178, alpha2: "cg", alpha3: "cog", flag: require("../assets/flags/32x32/cg.png"), zh: "刚果共和国", en: "Congo" },
  cd: { id: 180, alpha2: "cd", alpha3: "cod", flag: require("../assets/flags/32x32/cd.png"), zh: "刚果民主共和国", en: "Congo, Democratic Republic of the" },
  cr: { id: 188, alpha2: "cr", alpha3: "cri", flag: require("../assets/flags/32x32/cr.png"), zh: "哥斯达黎加", en: "Costa Rica" },
  ci: { id: 384, alpha2: "ci", alpha3: "civ", flag: require("../assets/flags/32x32/ci.png"), zh: "科特迪瓦", en: "Côte d'Ivoire" },
  hr: { id: 191, alpha2: "hr", alpha3: "hrv", flag: require("../assets/flags/32x32/hr.png"), zh: "克罗地亚", en: "Croatia" },
  cu: { id: 192, alpha2: "cu", alpha3: "cub", flag: require("../assets/flags/32x32/cu.png"), zh: "古巴", en: "Cuba" },
  cy: { id: 196, alpha2: "cy", alpha3: "cyp", flag: require("../assets/flags/32x32/cy.png"), zh: "塞浦路斯", en: "Cyprus" },
  cz: { id: 203, alpha2: "cz", alpha3: "cze", flag: require("../assets/flags/32x32/cz.png"), zh: "捷克", en: "Czechia" },
  dk: { id: 208, alpha2: "dk", alpha3: "dnk", flag: require("../assets/flags/32x32/dk.png"), zh: "丹麦", en: "Denmark" },
  dj: { id: 262, alpha2: "dj", alpha3: "dji", flag: require("../assets/flags/32x32/dj.png"), zh: "吉布提", en: "Djibouti" },
  dm: { id: 212, alpha2: "dm", alpha3: "dma", flag: require("../assets/flags/32x32/dm.png"), zh: "多米尼克", en: "Dominica" },
  do: { id: 214, alpha2: "do", alpha3: "dom", flag: require("../assets/flags/32x32/do.png"), zh: "多米尼加", en: "Dominican Republic" },
  ec: { id: 218, alpha2: "ec", alpha3: "ecu", flag: require("../assets/flags/32x32/ec.png"), zh: "厄瓜多尔", en: "Ecuador" },
  eg: { id: 818, alpha2: "eg", alpha3: "egy", flag: require("../assets/flags/32x32/eg.png"), zh: "埃及", en: "Egypt" },
  sv: { id: 222, alpha2: "sv", alpha3: "slv", flag: require("../assets/flags/32x32/sv.png"), zh: "萨尔瓦多", en: "El Salvador" },
  gq: { id: 226, alpha2: "gq", alpha3: "gnq", flag: require("../assets/flags/32x32/gq.png"), zh: "赤道几内亚", en: "Equatorial Guinea" },
  er: { id: 232, alpha2: "er", alpha3: "eri", flag: require("../assets/flags/32x32/er.png"), zh: "厄立特里亚", en: "Eritrea" },
  ee: { id: 233, alpha2: "ee", alpha3: "est", flag: require("../assets/flags/32x32/ee.png"), zh: "爱沙尼亚", en: "Estonia" },
  sz: { id: 748, alpha2: "sz", alpha3: "swz", flag: require("../assets/flags/32x32/sz.png"), zh: "斯威士兰", en: "Eswatini" },
  et: { id: 231, alpha2: "et", alpha3: "eth", flag: require("../assets/flags/32x32/et.png"), zh: "埃塞俄比亚", en: "Ethiopia" },
  fj: { id: 242, alpha2: "fj", alpha3: "fji", flag: require("../assets/flags/32x32/fj.png"), zh: "斐济", en: "Fiji" },
  fi: { id: 246, alpha2: "fi", alpha3: "fin", flag: require("../assets/flags/32x32/fi.png"), zh: "芬兰", en: "Finland" },
  fr: { id: 250, alpha2: "fr", alpha3: "fra", flag: require("../assets/flags/32x32/fr.png"), zh: "法国", en: "France" },
  ga: { id: 266, alpha2: "ga", alpha3: "gab", flag: require("../assets/flags/32x32/ga.png"), zh: "加蓬", en: "Gabon" },
  gm: { id: 270, alpha2: "gm", alpha3: "gmb", flag: require("../assets/flags/32x32/gm.png"), zh: "冈比亚", en: "Gambia" },
  ge: { id: 268, alpha2: "ge", alpha3: "geo", flag: require("../assets/flags/32x32/ge.png"), zh: "格鲁吉亚", en: "Georgia" },
  de: { id: 276, alpha2: "de", alpha3: "deu", flag: require("../assets/flags/32x32/de.png"), zh: "德国", en: "Germany" },
  gh: { id: 288, alpha2: "gh", alpha3: "gha", flag: require("../assets/flags/32x32/gh.png"), zh: "加纳", en: "Ghana" },
  gr: { id: 300, alpha2: "gr", alpha3: "grc", flag: require("../assets/flags/32x32/gr.png"), zh: "希腊", en: "Greece" },
  gd: { id: 308, alpha2: "gd", alpha3: "grd", flag: require("../assets/flags/32x32/gd.png"), zh: "格林纳达", en: "Grenada" },
  gt: { id: 320, alpha2: "gt", alpha3: "gtm", flag: require("../assets/flags/32x32/gt.png"), zh: "危地马拉", en: "Guatemala" },
  gn: { id: 324, alpha2: "gn", alpha3: "gin", flag: require("../assets/flags/32x32/gn.png"), zh: "几内亚", en: "Guinea" },
  gw: { id: 624, alpha2: "gw", alpha3: "gnb", flag: require("../assets/flags/32x32/gw.png"), zh: "几内亚比绍", en: "Guinea-Bissau" },
  gy: { id: 328, alpha2: "gy", alpha3: "guy", flag: require("../assets/flags/32x32/gy.png"), zh: "圭亚那", en: "Guyana" },
  ht: { id: 332, alpha2: "ht", alpha3: "hti", flag: require("../assets/flags/32x32/ht.png"), zh: "海地", en: "Haiti" },
  hn: { id: 340, alpha2: "hn", alpha3: "hnd", flag: require("../assets/flags/32x32/hn.png"), zh: "洪都拉斯", en: "Honduras" },
  hu: { id: 348, alpha2: "hu", alpha3: "hun", flag: require("../assets/flags/32x32/hu.png"), zh: "匈牙利", en: "Hungary" },
  is: { id: 352, alpha2: "is", alpha3: "isl", flag: require("../assets/flags/32x32/is.png"), zh: "冰岛", en: "Iceland" },
  in: { id: 356, alpha2: "in", alpha3: "ind", flag: require("../assets/flags/32x32/in.png"), zh: "印度", en: "India" },
  id: { id: 360, alpha2: "id", alpha3: "idn", flag: require("../assets/flags/32x32/id.png"), zh: "印度尼西亚", en: "Indonesia" },
  ir: { id: 364, alpha2: "ir", alpha3: "irn", flag: require("../assets/flags/32x32/ir.png"), zh: "伊朗", en: "Iran (Islamic Republic of)" },
  iq: { id: 368, alpha2: "iq", alpha3: "irq", flag: require("../assets/flags/32x32/iq.png"), zh: "伊拉克", en: "Iraq" },
  ie: { id: 372, alpha2: "ie", alpha3: "irl", flag: require("../assets/flags/32x32/ie.png"), zh: "爱尔兰", en: "Ireland" },
  il: { id: 376, alpha2: "il", alpha3: "isr", flag: require("../assets/flags/32x32/il.png"), zh: "以色列", en: "Israel" },
  it: { id: 380, alpha2: "it", alpha3: "ita", flag: require("../assets/flags/32x32/it.png"), zh: "意大利", en: "Italy" },
  jm: { id: 388, alpha2: "jm", alpha3: "jam", flag: require("../assets/flags/32x32/jm.png"), zh: "牙买加", en: "Jamaica" },
  jp: { id: 392, alpha2: "jp", alpha3: "jpn", flag: require("../assets/flags/32x32/jp.png"), zh: "日本", en: "Japan" },
  jo: { id: 400, alpha2: "jo", alpha3: "jor", flag: require("../assets/flags/32x32/jo.png"), zh: "约旦", en: "Jordan" },
  kz: { id: 398, alpha2: "kz", alpha3: "kaz", flag: require("../assets/flags/32x32/kz.png"), zh: "哈萨克斯坦", en: "Kazakhstan" },
  ke: { id: 404, alpha2: "ke", alpha3: "ken", flag: require("../assets/flags/32x32/ke.png"), zh: "肯尼亚", en: "Kenya" },
  ki: { id: 296, alpha2: "ki", alpha3: "kir", flag: require("../assets/flags/32x32/ki.png"), zh: "基里巴斯", en: "Kiribati" },
  kp: { id: 408, alpha2: "kp", alpha3: "prk", flag: require("../assets/flags/32x32/kp.png"), zh: "朝鲜", en: "Korea (Democratic People's Republic of)" },
  kr: { id: 410, alpha2: "kr", alpha3: "kor", flag: require("../assets/flags/32x32/kr.png"), zh: "韩国", en: "Korea, Republic of" },
  kw: { id: 414, alpha2: "kw", alpha3: "kwt", flag: require("../assets/flags/32x32/kw.png"), zh: "科威特", en: "Kuwait" },
  kg: { id: 417, alpha2: "kg", alpha3: "kgz", flag: require("../assets/flags/32x32/kg.png"), zh: "吉尔吉斯斯坦", en: "Kyrgyzstan" },
  la: { id: 418, alpha2: "la", alpha3: "lao", flag: require("../assets/flags/32x32/la.png"), zh: "老挝", en: "Lao People's Democratic Republic" },
  lv: { id: 428, alpha2: "lv", alpha3: "lva", flag: require("../assets/flags/32x32/lv.png"), zh: "拉脱维亚", en: "Latvia" },
  lb: { id: 422, alpha2: "lb", alpha3: "lbn", flag: require("../assets/flags/32x32/lb.png"), zh: "黎巴嫩", en: "Lebanon" },
  ls: { id: 426, alpha2: "ls", alpha3: "lso", flag: require("../assets/flags/32x32/ls.png"), zh: "莱索托", en: "Lesotho" },
  lr: { id: 430, alpha2: "lr", alpha3: "lbr", flag: require("../assets/flags/32x32/lr.png"), zh: "利比里亚", en: "Liberia" },
  ly: { id: 434, alpha2: "ly", alpha3: "lby", flag: require("../assets/flags/32x32/ly.png"), zh: "利比亚", en: "Libya" },
  li: { id: 438, alpha2: "li", alpha3: "lie", flag: require("../assets/flags/32x32/li.png"), zh: "列支敦士登", en: "Liechtenstein" },
  lt: { id: 440, alpha2: "lt", alpha3: "ltu", flag: require("../assets/flags/32x32/lt.png"), zh: "立陶宛", en: "Lithuania" },
  lu: { id: 442, alpha2: "lu", alpha3: "lux", flag: require("../assets/flags/32x32/lu.png"), zh: "卢森堡", en: "Luxembourg" },
  mg: { id: 450, alpha2: "mg", alpha3: "mdg", flag: require("../assets/flags/32x32/mg.png"), zh: "马达加斯加", en: "Madagascar" },
  mw: { id: 454, alpha2: "mw", alpha3: "mwi", flag: require("../assets/flags/32x32/mw.png"), zh: "马拉维", en: "Malawi" },
  my: { id: 458, alpha2: "my", alpha3: "mys", flag: require("../assets/flags/32x32/my.png"), zh: "马来西亚", en: "Malaysia" },
  mv: { id: 462, alpha2: "mv", alpha3: "mdv", flag: require("../assets/flags/32x32/mv.png"), zh: "马尔代夫", en: "Maldives" },
  ml: { id: 466, alpha2: "ml", alpha3: "mli", flag: require("../assets/flags/32x32/ml.png"), zh: "马里", en: "Mali" },
  mt: { id: 470, alpha2: "mt", alpha3: "mlt", flag: require("../assets/flags/32x32/mt.png"), zh: "马耳他", en: "Malta" },
  mh: { id: 584, alpha2: "mh", alpha3: "mhl", flag: require("../assets/flags/32x32/mh.png"), zh: "马绍尔群岛", en: "Marshall Islands" },
  mr: { id: 478, alpha2: "mr", alpha3: "mrt", flag: require("../assets/flags/32x32/mr.png"), zh: "毛里塔尼亚", en: "Mauritania" },
  mu: { id: 480, alpha2: "mu", alpha3: "mus", flag: require("../assets/flags/32x32/mu.png"), zh: "毛里求斯", en: "Mauritius" },
  mx: { id: 484, alpha2: "mx", alpha3: "mex", flag: require("../assets/flags/32x32/mx.png"), zh: "墨西哥", en: "Mexico" },
  fm: { id: 583, alpha2: "fm", alpha3: "fsm", flag: require("../assets/flags/32x32/fm.png"), zh: "密克罗尼西亚联邦", en: "Micronesia (Federated States of)" },
  md: { id: 498, alpha2: "md", alpha3: "mda", flag: require("../assets/flags/32x32/md.png"), zh: "摩尔多瓦", en: "Moldova, Republic of" },
  mc: { id: 492, alpha2: "mc", alpha3: "mco", flag: require("../assets/flags/32x32/mc.png"), zh: "摩纳哥", en: "Monaco" },
  mn: { id: 496, alpha2: "mn", alpha3: "mng", flag: require("../assets/flags/32x32/mn.png"), zh: "蒙古", en: "Mongolia" },
  me: { id: 499, alpha2: "me", alpha3: "mne", flag: require("../assets/flags/32x32/me.png"), zh: "黑山", en: "Montenegro" },
  ma: { id: 504, alpha2: "ma", alpha3: "mar", flag: require("../assets/flags/32x32/ma.png"), zh: "摩洛哥", en: "Morocco" },
  mz: { id: 508, alpha2: "mz", alpha3: "moz", flag: require("../assets/flags/32x32/mz.png"), zh: "莫桑比克", en: "Mozambique" },
  mm: { id: 104, alpha2: "mm", alpha3: "mmr", flag: require("../assets/flags/32x32/mm.png"), zh: "缅甸", en: "Myanmar" },
  na: { id: 516, alpha2: "na", alpha3: "nam", flag: require("../assets/flags/32x32/na.png"), zh: "纳米比亚", en: "Namibia" },
  nr: { id: 520, alpha2: "nr", alpha3: "nru", flag: require("../assets/flags/32x32/nr.png"), zh: "瑙鲁", en: "Nauru" },
  np: { id: 524, alpha2: "np", alpha3: "npl", flag: require("../assets/flags/32x32/np.png"), zh: "尼泊尔", en: "Nepal" },
  nl: { id: 528, alpha2: "nl", alpha3: "nld", flag: require("../assets/flags/32x32/nl.png"), zh: "荷兰", en: "Netherlands" },
  nz: { id: 554, alpha2: "nz", alpha3: "nzl", flag: require("../assets/flags/32x32/nz.png"), zh: "新西兰", en: "New Zealand" },
  ni: { id: 558, alpha2: "ni", alpha3: "nic", flag: require("../assets/flags/32x32/ni.png"), zh: "尼加拉瓜", en: "Nicaragua" },
  ne: { id: 562, alpha2: "ne", alpha3: "ner", flag: require("../assets/flags/32x32/ne.png"), zh: "尼日尔", en: "Niger" },
  ng: { id: 566, alpha2: "ng", alpha3: "nga", flag: require("../assets/flags/32x32/ng.png"), zh: "尼日利亚", en: "Nigeria" },
  mk: { id: 807, alpha2: "mk", alpha3: "mkd", flag: require("../assets/flags/32x32/mk.png"), zh: "北马其顿", en: "North Macedonia" },
  no: { id: 578, alpha2: "no", alpha3: "nor", flag: require("../assets/flags/32x32/no.png"), zh: "挪威", en: "Norway" },
  om: { id: 512, alpha2: "om", alpha3: "omn", flag: require("../assets/flags/32x32/om.png"), zh: "阿曼", en: "Oman" },
  pk: { id: 586, alpha2: "pk", alpha3: "pak", flag: require("../assets/flags/32x32/pk.png"), zh: "巴基斯坦", en: "Pakistan" },
  pw: { id: 585, alpha2: "pw", alpha3: "plw", flag: require("../assets/flags/32x32/pw.png"), zh: "帕劳", en: "Palau" },
  pa: { id: 591, alpha2: "pa", alpha3: "pan", flag: require("../assets/flags/32x32/pa.png"), zh: "巴拿马", en: "Panama" },
  pg: { id: 598, alpha2: "pg", alpha3: "png", flag: require("../assets/flags/32x32/pg.png"), zh: "巴布亚新几内亚", en: "Papua New Guinea" },
  py: { id: 600, alpha2: "py", alpha3: "pry", flag: require("../assets/flags/32x32/py.png"), zh: "巴拉圭", en: "Paraguay" },
  pe: { id: 604, alpha2: "pe", alpha3: "per", flag: require("../assets/flags/32x32/pe.png"), zh: "秘鲁", en: "Peru" },
  ph: { id: 608, alpha2: "ph", alpha3: "phl", flag: require("../assets/flags/32x32/ph.png"), zh: "菲律宾", en: "Philippines" },
  pl: { id: 616, alpha2: "pl", alpha3: "pol", flag: require("../assets/flags/32x32/pl.png"), zh: "波兰", en: "Poland" },
  pt: { id: 620, alpha2: "pt", alpha3: "prt", flag: require("../assets/flags/32x32/pt.png"), zh: "葡萄牙", en: "Portugal" },
  qa: { id: 634, alpha2: "qa", alpha3: "qat", flag: require("../assets/flags/32x32/qa.png"), zh: "卡塔尔", en: "Qatar" },
  ro: { id: 642, alpha2: "ro", alpha3: "rou", flag: require("../assets/flags/32x32/ro.png"), zh: "罗马尼亚", en: "Romania" },
  ru: { id: 643, alpha2: "ru", alpha3: "rus", flag: require("../assets/flags/32x32/ru.png"), zh: "俄罗斯", en: "Russian Federation" },
  rw: { id: 646, alpha2: "rw", alpha3: "rwa", flag: require("../assets/flags/32x32/rw.png"), zh: "卢旺达", en: "Rwanda" },
  kn: { id: 659, alpha2: "kn", alpha3: "kna", flag: require("../assets/flags/32x32/kn.png"), zh: "圣基茨和尼维斯", en: "Saint Kitts and Nevis" },
  lc: { id: 662, alpha2: "lc", alpha3: "lca", flag: require("../assets/flags/32x32/lc.png"), zh: "圣卢西亚", en: "Saint Lucia" },
  vc: { id: 670, alpha2: "vc", alpha3: "vct", flag: require("../assets/flags/32x32/vc.png"), zh: "圣文森特和格林纳丁斯", en: "Saint Vincent and the Grenadines" },
  ws: { id: 882, alpha2: "ws", alpha3: "wsm", flag: require("../assets/flags/32x32/ws.png"), zh: "萨摩亚", en: "Samoa" },
  sm: { id: 674, alpha2: "sm", alpha3: "smr", flag: require("../assets/flags/32x32/sm.png"), zh: "圣马力诺", en: "San Marino" },
  st: { id: 678, alpha2: "st", alpha3: "stp", flag: require("../assets/flags/32x32/st.png"), zh: "圣多美和普林西比", en: "Sao Tome and Principe" },
  sa: { id: 682, alpha2: "sa", alpha3: "sau", flag: require("../assets/flags/32x32/sa.png"), zh: "沙特阿拉伯", en: "Saudi Arabia" },
  sn: { id: 686, alpha2: "sn", alpha3: "sen", flag: require("../assets/flags/32x32/sn.png"), zh: "塞内加尔", en: "Senegal" },
  rs: { id: 688, alpha2: "rs", alpha3: "srb", flag: require("../assets/flags/32x32/rs.png"), zh: "塞尔维亚", en: "Serbia" },
  sc: { id: 690, alpha2: "sc", alpha3: "syc", flag: require("../assets/flags/32x32/sc.png"), zh: "塞舌尔", en: "Seychelles" },
  sl: { id: 694, alpha2: "sl", alpha3: "sle", flag: require("../assets/flags/32x32/sl.png"), zh: "塞拉利昂", en: "Sierra Leone" },
  sg: { id: 702, alpha2: "sg", alpha3: "sgp", flag: require("../assets/flags/32x32/sg.png"), zh: "新加坡", en: "Singapore" },
  sk: { id: 703, alpha2: "sk", alpha3: "svk", flag: require("../assets/flags/32x32/sk.png"), zh: "斯洛伐克", en: "Slovakia" },
  si: { id: 705, alpha2: "si", alpha3: "svn", flag: require("../assets/flags/32x32/si.png"), zh: "斯洛文尼亚", en: "Slovenia" },
  sb: { id: 90, alpha2: "sb", alpha3: "slb", flag: require("../assets/flags/32x32/sb.png"), zh: "所罗门群岛", en: "Solomon Islands" },
  so: { id: 706, alpha2: "so", alpha3: "som", flag: require("../assets/flags/32x32/so.png"), zh: "索马里", en: "Somalia" },
  za: { id: 710, alpha2: "za", alpha3: "zaf", flag: require("../assets/flags/32x32/za.png"), zh: "南非", en: "South Africa" },
  ss: { id: 728, alpha2: "ss", alpha3: "ssd", flag: require("../assets/flags/32x32/ss.png"), zh: "南苏丹", en: "South Sudan" },
  es: { id: 724, alpha2: "es", alpha3: "esp", flag: require("../assets/flags/32x32/es.png"), zh: "西班牙", en: "Spain" },
  lk: { id: 144, alpha2: "lk", alpha3: "lka", flag: require("../assets/flags/32x32/lk.png"), zh: "斯里兰卡", en: "Sri Lanka" },
  sd: { id: 729, alpha2: "sd", alpha3: "sdn", flag: require("../assets/flags/32x32/sd.png"), zh: "苏丹", en: "Sudan" },
  sr: { id: 740, alpha2: "sr", alpha3: "sur", flag: require("../assets/flags/32x32/sr.png"), zh: "苏里南", en: "Suriname" },
  se: { id: 752, alpha2: "se", alpha3: "swe", flag: require("../assets/flags/32x32/se.png"), zh: "瑞典", en: "Sweden" },
  ch: { id: 756, alpha2: "ch", alpha3: "che", flag: require("../assets/flags/32x32/ch.png"), zh: "瑞士", en: "Switzerland" },
  sy: { id: 760, alpha2: "sy", alpha3: "syr", flag: require("../assets/flags/32x32/sy.png"), zh: "叙利亚", en: "Syrian Arab Republic" },
  tj: { id: 762, alpha2: "tj", alpha3: "tjk", flag: require("../assets/flags/32x32/tj.png"), zh: "塔吉克斯坦", en: "Tajikistan" },
  tz: { id: 834, alpha2: "tz", alpha3: "tza", flag: require("../assets/flags/32x32/tz.png"), zh: "坦桑尼亚", en: "Tanzania, United Republic of" },
  th: { id: 764, alpha2: "th", alpha3: "tha", flag: require("../assets/flags/32x32/th.png"), zh: "泰国", en: "Thailand" },
  tl: { id: 626, alpha2: "tl", alpha3: "tls", flag: require("../assets/flags/32x32/tl.png"), zh: "东帝汶", en: "Timor-Leste" },
  tg: { id: 768, alpha2: "tg", alpha3: "tgo", flag: require("../assets/flags/32x32/tg.png"), zh: "多哥", en: "Togo" },
  to: { id: 776, alpha2: "to", alpha3: "ton", flag: require("../assets/flags/32x32/to.png"), zh: "汤加", en: "Tonga" },
  tt: { id: 780, alpha2: "tt", alpha3: "tto", flag: require("../assets/flags/32x32/tt.png"), zh: "特立尼达和多巴哥", en: "Trinidad and Tobago" },
  tn: { id: 788, alpha2: "tn", alpha3: "tun", flag: require("../assets/flags/32x32/tn.png"), zh: "突尼斯", en: "Tunisia" },
  tr: { id: 792, alpha2: "tr", alpha3: "tur", flag: require("../assets/flags/32x32/tr.png"), zh: "土耳其", en: "Türkiye" },
  tm: { id: 795, alpha2: "tm", alpha3: "tkm", flag: require("../assets/flags/32x32/tm.png"), zh: "土库曼斯坦", en: "Turkmenistan" },
  tv: { id: 798, alpha2: "tv", alpha3: "tuv", flag: require("../assets/flags/32x32/tv.png"), zh: "图瓦卢", en: "Tuvalu" },
  ug: { id: 800, alpha2: "ug", alpha3: "uga", flag: require("../assets/flags/32x32/ug.png"), zh: "乌干达", en: "Uganda" },
  ua: { id: 804, alpha2: "ua", alpha3: "ukr", flag: require("../assets/flags/32x32/ua.png"), zh: "乌克兰", en: "Ukraine" },
  ae: { id: 784, alpha2: "ae", alpha3: "are", flag: require("../assets/flags/32x32/ae.png"), zh: "阿联酋", en: "United Arab Emirates" },
  gb: { id: 826, alpha2: "gb", alpha3: "gbr", flag: require("../assets/flags/32x32/gb.png"), zh: "英国", en: "United Kingdom of Great Britain and Northern Ireland" },
  us: { id: 840, alpha2: "us", alpha3: "usa", flag: require("../assets/flags/32x32/us.png"), zh: "美国", en: "United States of America" },
  uy: { id: 858, alpha2: "uy", alpha3: "ury", flag: require("../assets/flags/32x32/uy.png"), zh: "乌拉圭", en: "Uruguay" },
  uz: { id: 860, alpha2: "uz", alpha3: "uzb", flag: require("../assets/flags/32x32/uz.png"), zh: "乌兹别克斯坦", en: "Uzbekistan" },
  vu: { id: 548, alpha2: "vu", alpha3: "vut", flag: require("../assets/flags/32x32/vu.png"), zh: "瓦努阿图", en: "Vanuatu" },
  ve: { id: 862, alpha2: "ve", alpha3: "ven", flag: require("../assets/flags/32x32/ve.png"), zh: "委内瑞拉", en: "Venezuela (Bolivarian Republic of)" },
  vn: { id: 704, alpha2: "vn", alpha3: "vnm", flag: require("../assets/flags/32x32/vn.png"), zh: "越南", en: "Viet Nam" },
  ye: { id: 887, alpha2: "ye", alpha3: "yem", flag: require("../assets/flags/32x32/ye.png"), zh: "也门", en: "Yemen" },
  zm: { id: 894, alpha2: "zm", alpha3: "zmb", flag: require("../assets/flags/32x32/zm.png"), zh: "赞比亚", en: "Zambia" },
  zw: { id: 716, alpha2: "zw", alpha3: "zwe", flag: require("../assets/flags/32x32/zw.png"), zh: "津巴布韦", en: "Zimbabwe" },
};
