name: Expo Preview

on:
  pull_request:
    paths:
      - package.json
      - 'src/**/*'
      - '.github/workflows/**'
      - '**.lock'
      - "**.patch"

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.common

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        with:
          command: eas update --branch pr_preview --auto
