name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: macos-latest
    permissions:
      pull-requests: write
      contents: write
      actions: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Dependencies
        run: yarn
      
      - name: Resolve release type
        uses: actions/github-script@v6
        id: release-type
        with:
          result-encoding: string
          script: |
            const resolveReleaseType = require('./scripts/resolve-release-type.js')
            const releaseType = await resolveReleaseType();
            return releaseType
            
      - name: Bump Versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: changesets/action@v1
        with:
          version: yarn run release:version
          publish: yarn run release:publish
          commit: 'chore: update versions'
          title: 'chore: update versions'

      - name: Trigger Publish Preview workflow
        if: steps.release-type.outputs.result != ''
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: preview.yml
          inputs: '{ "release_type": "${{ steps.release-type.outputs.result }}" }'