name: Expo Release Update

on:
  push:
    branches:
      - staging

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.common

      - name: Install dependencies
        run: yarn install
        
      # Fetch the main branch for the changeset check
      - name: Fetch main branch
        run: |
          git fetch origin main:main

      # If there are changesets, stop the workflow, because we don't want to publish a release update for the version that hasn't been released yet.
      - name: Check for changesets
        id: changeset_check
        run: |
          set +e
          yarn changeset status
          exit_status=$?
          set -e
          if [ $exit_status -eq 0 ]; then
            echo "Changeset found. Stopping the workflow."
            echo "::set-output name=has_changeset::true"
            exit 1
          else
            echo "No changesets found. Continuing with the workflow."
            echo "::set-output name=has_changeset::false"
          fi

      - name: Publish update
        if: steps.changeset_check.outputs.has_changeset == 'false'
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: eas update --branch "${GITHUB_REF#refs/heads/}" --auto

